[tool]
id = "com.byrne.stopwatch"
label = "Stopwatch"
versionCode = 1
versionName = "1.0"
permissions = []
# Use com.thelightphone.sdk.emulator for local emulator builds.
serverPackage = "com.lightos"
